// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Filicon",
    defaultLocalization: "en",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "FiliconDomain", targets: ["FiliconDomain"]),
        .library(name: "FiliconProviderKit", targets: ["FiliconProviderKit"]),
        .library(name: "FiliconPersistence", targets: ["FiliconPersistence"]),
        .library(name: "FiliconMCP", targets: ["FiliconMCP"]),
        .library(name: "FiliconAgents", targets: ["FiliconAgents"]),
        .library(name: "FiliconChannels", targets: ["FiliconChannels"]),
        .library(name: "FiliconAutomations", targets: ["FiliconAutomations"]),
        .library(name: "FiliconAppServices", targets: ["FiliconAppServices"]),
        .library(name: "FiliconLocalTools", targets: ["FiliconLocalTools"]),
        .library(name: "FiliconUpdater", targets: ["FiliconUpdater"]),
        .library(name: "FiliconVoice", targets: ["FiliconVoice"]),
        .library(name: "FiliconSettings", targets: ["FiliconSettings"]),
        .library(name: "FiliconComputer", targets: ["FiliconComputer"]),
        .library(name: "FiliconPlugins", targets: ["FiliconPlugins"]),
        .library(name: "FiliconSharedRooms", targets: ["FiliconSharedRooms"]),
        .library(name: "FiliconAccount", targets: ["FiliconAccount"]),
        .library(name: "FiliconAutoReview", targets: ["FiliconAutoReview"]),
        .library(name: "FiliconRichContent", targets: ["FiliconRichContent"]),
        .library(name: "FiliconSecurityKey", targets: ["FiliconSecurityKey"]),
        .executable(name: "FiliconLocalToolHelper", targets: ["FiliconLocalToolHelper"]),
        .executable(name: "FiliconLocalToolXPCService", targets: ["FiliconLocalToolXPCService"]),
        .executable(name: "FiliconUpdateHelper", targets: ["FiliconUpdateHelper"]),
        .executable(name: "Filicon", targets: ["Filicon"]),
    ],
    dependencies: [
        .package(url: "https://github.com/pointfreeco/swift-custom-dump", from: "1.3.3"),
    ],
    targets: [
        .target(name: "FiliconDomain"),
        .target(name: "FiliconProviderKit", dependencies: ["FiliconDomain"]),
        .systemLibrary(name: "CSQLite"),
        .target(name: "FiliconPersistence", dependencies: ["FiliconDomain", "CSQLite"]),
        .target(name: "FiliconMCP"),
        .target(name: "FiliconAgents", dependencies: ["FiliconDomain"]),
        .target(name: "FiliconChannels"),
        .target(name: "FiliconAutomations"),
        .target(name: "FiliconAppServices", dependencies: ["FiliconDomain", "FiliconProviderKit", "FiliconPersistence", "FiliconAgents", "FiliconAutomations"]),
        .target(name: "FiliconLocalTools", dependencies: ["FiliconDomain"], exclude: ["XPC_INTEGRATION.md"]),
        .target(name: "FiliconUpdater"),
        .target(name: "FiliconVoice"),
        .target(name: "FiliconSettings", dependencies: ["FiliconDomain"]),
        .target(name: "FiliconComputer"),
        .target(name: "FiliconPlugins"),
        .target(name: "FiliconSharedRooms"),
        .target(name: "FiliconAccount", linkerSettings: [.linkedFramework("Security")]),
        .target(name: "FiliconAutoReview", dependencies: ["FiliconDomain"]),
        .target(name: "FiliconRichContent"),
        .target(
            name: "FiliconSecurityKey",
            dependencies: ["FiliconComputer"],
            linkerSettings: [.linkedFramework("AuthenticationServices"), .linkedFramework("AppKit")]
        ),
        .executableTarget(name: "FiliconLocalToolHelper", dependencies: ["FiliconLocalTools"]),
        .executableTarget(name: "FiliconLocalToolXPCService", dependencies: ["FiliconLocalTools"]),
        .executableTarget(name: "FiliconUpdateHelper", dependencies: ["FiliconUpdater"]),
        .executableTarget(
            name: "Filicon",
            dependencies: ["FiliconDomain", "FiliconProviderKit", "FiliconAppServices", "FiliconAgents", "FiliconChannels", "FiliconAutomations", "FiliconMCP", "FiliconVoice", "FiliconLocalTools", "FiliconUpdater", "FiliconSettings", "FiliconComputer", "FiliconPlugins", "FiliconSharedRooms", "FiliconAccount", "FiliconAutoReview", "FiliconRichContent", "FiliconSecurityKey"],
            resources: [.process("Resources")]
        ),
        .testTarget(name: "FiliconTests", dependencies: ["FiliconDomain", "FiliconProviderKit", "FiliconPersistence", "FiliconAppServices", "FiliconAgents", "CSQLite", .product(name: "CustomDump", package: "swift-custom-dump")]),
        .testTarget(name: "FiliconMCPTests", dependencies: ["FiliconMCP"]),
        .testTarget(name: "FiliconAgentsTests", dependencies: ["FiliconAgents", "FiliconDomain"]),
        .testTarget(name: "FiliconChannelsTests", dependencies: ["FiliconChannels"]),
        .testTarget(name: "FiliconAutomationsTests", dependencies: ["FiliconAutomations"]),
        .testTarget(name: "FiliconLocalToolsTests", dependencies: ["FiliconLocalTools"]),
        .testTarget(name: "FiliconUpdaterTests", dependencies: ["FiliconUpdater"]),
        .testTarget(name: "FiliconVoiceTests", dependencies: ["FiliconVoice"]),
        .testTarget(name: "FiliconSettingsTests", dependencies: ["FiliconSettings", "FiliconDomain"]),
        .testTarget(name: "FiliconComputerTests", dependencies: ["FiliconComputer"]),
        .testTarget(name: "FiliconPluginsTests", dependencies: ["FiliconPlugins"]),
        .testTarget(name: "FiliconSharedRoomsTests", dependencies: ["FiliconSharedRooms"]),
        .testTarget(name: "FiliconAccountTests", dependencies: ["FiliconAccount"]),
        .testTarget(name: "FiliconAutoReviewTests", dependencies: ["FiliconAutoReview", "FiliconDomain"]),
        .testTarget(name: "FiliconAttachmentPreviewTests", dependencies: ["Filicon", "FiliconDomain", "FiliconProviderKit", "FiliconAppServices", "FiliconPersistence", "FiliconAgents", "FiliconRichContent", "FiliconAutoReview", "FiliconMCP", "FiliconSecurityKey", .product(name: "CustomDump", package: "swift-custom-dump")]),
        .testTarget(name: "FiliconRichContentTests", dependencies: ["FiliconRichContent"]),
        .testTarget(name: "FiliconSecurityKeyTests", dependencies: ["FiliconSecurityKey"]),
    ]
)
